//
// Created by svalov on 7/20/16.
//

#ifndef MOARSTACK_FUNCRESULTS_H
#define MOARSTACK_FUNCRESULTS_H

#define FUNC_RESULT_SUCCESS 0
#define FUNC_RESULT_FAILED -1
#define FUNC_RESULT_FAILED_ARGUMENT -2
#define FUNC_RESULT_FAILED_IO -3
#define FUNC_RESULT_FAILED_MEM_ALLOCATION -4
#define FUNC_RESULT_FAILED_NEIGHBORS -5
#endif //MOARSTACK_FUNCRESULTS_H

